### ISSUE TITLE
Bug: Overflow cutting off labs

### ISSUE THREAD

**Issue by tkaragianes** [eternagame/eterna-mobile#26]

**Comment by tkaragianes** [comment]
"After opening the app and moving from Home to Labs, the labs are cut off. But if you switch out and back within the same session, it seems to show the labs normally again:"

![image](https://user-images.githubusercontent.com/5233226/155390603-341d46ed-ccd3-4425-873e-b9fdeb80fd71.png)

**Comment by tkaragianes** [comment]
Haven't been able to reproduce this locally. @luxaritas have you seen this bug?

**Comment by luxaritas** [comment]
I haven't seen this, but the cutoff point seems to align with the padding of `#puzzle-scroll` - which also doesn't seem to have any effect?

![image](https://user-images.githubusercontent.com/18635705/156087770-e5535a37-2353-4006-95e7-9f43860f855d.png)

**Comment by luxaritas** [comment]
Er, I guess looking at it again it doesn't quite match, but regardless I don't see anything that should cause this...

**Comment by luxaritas** [comment]
Ran a test build on my iPhone SE, and I am able to consistently reproduce this - I'll look into it
