### ISSUE TITLE
Hide "Load More" labs button when all labs are loaded

### ISSUE THREAD

**Issue by tkaragianes** [eternagame/eterna-mobile#30]
"Within the Labs menu - if you reach the end of the Labs and click "Load More Labs", the button stays looking selected/on but never switches off or gives a message saying the end of the list was reached"

**Comment by tkaragianes** [comment]
Tested it out, and on dev at least, there's 457 labs. Two big problems to implementing this right now:
- 1: The server doesn't implement pagination, and it doesn't distinguish if you've asked for all the available data. Any request made for more than the available labs, the server just returns as many as it can give you in the requested size. If I ask for 500, the server will send all 457.
- 2: Because there's no pagination, every request sends all the data. So the initial request for 9 labs is fine. Click "Load More" and it will ask for 18 labs, and it will receive the data of the first 9 labs again. Click "Load More" again, get sent more duplicated data. 

I think the right move here is to address this with the server refactor, and implement pagination properly in the new backend. Then we can implement a response that tells the frontend "End of data", and can hide "Load More" in response. Pagination will also have the benefit of reducing responses with duplicate data.

**Comment by luxaritas** [comment]
The server _does_ actually implement pagination. The API supports a `skip` parameter, and the API call does return a total count (the app just currently throws it away)

**Comment by luxaritas** [comment]
Yeah, it was implemented in the old frontend, but got stuck in a WIP PR in the new frontend: https://github.com/eternagame/eternagame.org/pull/215
