### ISSUE TITLE
App update prompts

### ISSUE THREAD

**Issue by tkaragianes** [eternagame/eterna-mobile#37]
Leonard asked about how users will be prompted about mobile app updates. He went to show Eterna mobile to someone, and the mobile app was limited to tutorial puzzles only, and he wondered if he'd missed an app update.

**Comment by luxaritas** [comment]
I have implemented a mechanism for incrementing a version number in the backend, and hardcoding a version in the app where if the version returned by the backend is higher, it refuses to operate until you update. This was primarily intended for backwards-incompatible updates where using an old version of the app could cause issues.

Personally, I think relying on the app store for indicating other available updates should be fine - and this is how almost all apps work. Both the iOS app store and Google Play store also install updates automatically at some point, afaik.
