### ISSUE TITLE
Bug: Info screen exit incorrectly flashes tutorials screen

### ISSUE THREAD

**Issue by sbutkovi** [eternagame/eterna-mobile#39]
When logged in and user has finished tutorials: Going to the info screen ("i" on the main page) works fine but after you X out of it, it briefly shows the "logged out" view (i.e., the view of the tutorials - except it still shows the logged-in username) - happens very quickly and not all of the time, but it does happen (and managed to catch a screenshot of it). Tested on 1.4.1 on iPhone 8.
![pic1](https://user-images.githubusercontent.com/35237235/155814157-646c569d-f83c-4194-b078-0c1a177f5f72.PNG)
![pic2](https://user-images.githubusercontent.com/35237235/155814170-4b016657-dfef-43db-a94f-3d4f718b808b.png)

**Comment by luxaritas** [comment]
Tested a few times on the upcoming 1.4.2 and it doesn't look like this is an issue any more. Please re-open if it still occurs once we get a new build out
