### ISSUE TITLE
Update formatting in puzzle descriptions

### ISSUE THREAD

**Issue by sbutkovi** [eternagame/eterna-mobile#48]
Puzzle descriptions - would be nice if italics/etc. showed up analogously to the website version (example - see last line in attached). Tested on 1.4.1 on iPhone 8.

![pic1](https://user-images.githubusercontent.com/35237235/155816155-2e33395a-6e0f-4621-9637-fda556154569.PNG)

**Comment by luxaritas** [comment]
On the website we run the descriptions through v-dompurify-html to ensure it's sanitized while still maintaining formatting
