### ISSUE TITLE
Thumbnails get stretched when selected

### ISSUE THREAD

**Issue by sbutkovi** [eternagame/eterna-mobile#67]
This observed behavior is more silly than it is deleterious. When I open the Quests page, the icons look a certain way. When I push and hold on them with my finger, the icons get stretched (and then revert back to normal when automatically unselected after a second or so).

![quest_stretch_1](https://user-images.githubusercontent.com/35237235/158699511-c155039d-a27a-4ed1-877c-3d98ce01e518.png)
![quest_stretch_2](https://user-images.githubusercontent.com/35237235/158699526-7ba29177-c524-4b35-9962-ae98caf0062b.png)

Worth noting this is true for not just the thumbnails in Quests, but also at least some of the thumbnails in Labs. It also seems like some thumbnails are more affected by "stretching" than others.

**Comment by sbutkovi** [comment]
I just discovered this happens with more than just the Quests thumbnails - for example, it can be done with the Eterna logo on the top-left of many pages.

**Comment by luxaritas** [comment]
I think this is coming from the feature on iOS where when you tap and hold on an image, it lets you drag it around, and it's probably ignoring the `object-fit: contain;`. The solution here appears to be adding `-webkit-user-drag: none;` on the img elements on all the cards
