### ISSUE TITLE
Non-tutorial quests not as functional/useful as on the website

### ISSUE THREAD

**Issue by sbutkovi** [eternagame/eterna-mobile#71]
The summary is that non-tutorial quests could probably benefit from having filters and/or being able to view more puzzles than the default number shown (assuming the player's goal is to progress through quests and level up badges). This is probably easiest for me to explain with some concrete examples:

- For the Eterna100 quest, I am shown 20 puzzles on the mobile app (seemingly the 20 most-solved ones). One issue is that I have already solved all of these puzzles. I know that the Eterna100 collection is more than just these 20 puzzles, but without being able to view more puzzles or filter out ones I've already solved, I'm unable to (easily) progres further on this quest just through the app (I would need to somehow find the puzzles myself).

![eterna100](https://user-images.githubusercontent.com/35237235/158744459-a7e57a84-0189-4774-b7bb-a5b86c1ec175.png)

- For the Just for Fun quest, I am also only shown 20 puzzles (a mix of solved and unsolved ones). Visually, it looks like these might be listed in a chronological order rather than being sorted by "most solved" like for the Eterna100 quest. Regardless, I know that this quest/badge involves more than just these 20 puzzles, but you wouldn't be able to infer that through the current app.

**Comment by luxaritas** [comment]
I thought I had set these up so that they didn't have a limit of how many they pulled back - need to fix that. Most of these have few enough puzzles that I'm not super concerned about filters, though maybe at least an uncleared option would be good...
