### ISSUE TITLE
Carousel shows wrong number of lab submissions upon logging out

### ISSUE THREAD

**Issue by sbutkovi** [eternagame/eterna-mobile#74]
When I'm logged in, the carousel seems to correctly show the number of submissions I have to a lab:

![carousel_1](https://user-images.githubusercontent.com/35237235/158876208-b28da2c8-0390-4881-b2dc-1d871c8df1f2.png)

However, right when I log out and get sent back to the carousel screen, the displayed number of lab submissions is unusual - not only are the numbers incorrect, but they also go outside of the listed bounds for the number of submissions.

![carousel_2](https://user-images.githubusercontent.com/35237235/158876212-7cfddf9c-7c4f-4e54-aeb9-43fca5572a8c.png)
![carousel_3](https://user-images.githubusercontent.com/35237235/158876223-420509b8-88e7-42f4-8806-daee4b7c812b.png)

It's possible this bug is technically not specific to mobile - however, on the website version of the game, the player typically does not see the carousel screen upon logging out.

**Comment by luxaritas** [comment]
Logging out should send you back to the tutorial screen - this is fixed in the quest branch
