### ISSUE TITLE
Profile name stays highlighted even after closing options menu

### ISSUE THREAD

**Issue by sbutkovi** [eternagame/eterna-mobile#76]
The username has certain formatting when unselected, and then different formatting (different text color, dark background) when selected to open the options menu. Even after this options menu is closed, the username formatting does not revert back to its original look.

![pic1](https://user-images.githubusercontent.com/35237235/158884892-13d9fd95-8f07-455e-815e-c42279b5af0c.PNG)
![pic2](https://user-images.githubusercontent.com/35237235/158884851-f7479884-58aa-4b9b-b43d-c1837c7dd262.png)
![pic3](https://user-images.githubusercontent.com/35237235/158884880-51599da1-94dc-4f5b-8f57-08f705bfeb99.png)

**Comment by tkaragianes** [comment]
Interesting. Note the outline in the third screenshot. That implies that the element has focus still, which could explain why it has the active styling. I'll look into this, seems like a vue-bootstrap in a mobile app thing.

**Comment by sbutkovi** [comment]
I have been informed that this is the desired behavior (focus highlighting) and is an accessibility feature.
