### ISSUE TITLE
What should be accessible by the user upon logging out?

### ISSUE THREAD

**Issue by sbutkovi** [eternagame/eterna-mobile#94]
I will provide a screenshot-guided walkthrough for what currently happens. I start by logging out:

![pic1](https://user-images.githubusercontent.com/35237235/160182952-3a434685-ae66-4145-ad61-64cc51c22339.PNG)

I am taken to the home page, with the Labs, Quests, and Puzzles tabs visible (aside: the "time until synthesis" and "number of submissions" appear incorrect in this screenshot):

![pic2](https://user-images.githubusercontent.com/35237235/160182981-329a4783-8660-4da4-9584-a4930ae43008.png)

I can navigate to the Labs page:

![pic3](https://user-images.githubusercontent.com/35237235/160183063-5466d74e-bc78-44f8-a2a6-97974bd55ffa.png)

I can navigate to the Quests page:

![pic4](https://user-images.githubusercontent.com/35237235/160183070-99aa1f97-3776-4cac-b830-035f2c223d70.png)

I can navigate to the Puzzles page, but note that now there is only the Home tab visible:

![pic5](https://user-images.githubusercontent.com/35237235/160183080-d0f90685-1c31-4d98-bef7-9fdc06a12d25.png)

Now when I click on the Home tab, I am taken to the following screen:

![pic6](https://user-images.githubusercontent.com/35237235/160183090-cc82228a-d900-4812-9c6d-54f28322080f.png)

**Comment by luxaritas** [comment]
It _should_ be sending you back to the new user homepage after logging out, and it works on the browser mode but not on an actual device for some reason. I'll need to investigate
