### ISSUE TITLE
For new user, Single State filter on tutorials has unexpected behavior

### ISSUE THREAD

**Issue by sbutkovi** [eternagame/eterna-mobile#95]
It looks fine with no filters:

![pic1](https://user-images.githubusercontent.com/35237235/160184752-5169f610-8c83-4844-8f9c-a5e058e473ca.jpg)

The Uncleared filter appears to work as expected (in the case where no puzzles are solved yet):

![pic2](https://user-images.githubusercontent.com/35237235/160184760-1aaa386a-827a-4197-850d-77c5c1cae31e.jpg)

But when the Single State filter is chosen, some puzzles are incorrectly shown as being solved (the puzzles are also out of order):

![pic3](https://user-images.githubusercontent.com/35237235/160184554-7efaf4ae-a4e9-4c7b-8db8-9988a6cb2ddf.png)

![pic4](https://user-images.githubusercontent.com/35237235/160184562-5c5c740e-5baa-4f0d-8cbb-ed6d38e715c5.png)

Additionally, with this filter on, the user can access puzzles that haven't been unlocked yet:

![pic5](https://user-images.githubusercontent.com/35237235/160184574-ed411af9-d431-49c1-affa-ef545575841a.png)

Worth noting that this behavior occurs regardless of whether I had previously logged in with a post-tutorial account or I was testing on a fresh installation.

**Comment by luxaritas** [comment]
This is due to an idiosyncrasy with the way we need to handle this for incognito accounts. We should just remove the filters when accessing these as a user who hasn't unlocked lab access
